superdesk/superdesk-fi

client/package.json
client/superdesk.config.js
server/data/vocabularies.json
server/settings.py

- SDFID-20: Create custom field "Franchise" with controlled vocabulary
- SDFID-21: Create custom field "Compliance checked"
- SDFID-22: Custom field: "Featured content"
- SDFID-23: Create custom field "Content Style" with controlled
vocabulary
- SDFID-24: Create custom field "Author" with controlled vocabulary

added custom fields for SDFID-9

---

client/package.json

Reverts superdesk/superdesk-fidelity#32

Revert "test(vocabularies): Temporary PR: Add logs to debug categories"

---

server/templates/account_created.html
server/templates/account_created.txt

Replaces URL to UAT environment, fidelity-next.superdesk.pro by fidel…ity-uat.superdesk.pro

Fix URL in welcome to user template

---

client/package.json
server/requirements.txt

Needed by [SDFID-112](https://dev.sourcefabric.org/browse/SDFID-112)

Update cores, gunicorn and honcho

---

server/requirements.txt

there is fix for package publishing to content api

update server core

---

server/fidelity/privacy_policy.py
server/settings.py
server/templates/fidelity_layout.html
server/templates/oauth_authorized.html
server/templates/privacy_policy.html
server/templates/privacy_policy_users.html

it's hooking into saml auth to render privacy policy if user has not accepted it.
plus adding a status page with users and their acceptance status

feat privacy policy

---

client/package.json
server/requirements.txt

updated client-core to get SDFID-195 fix

updated cores

---

server/data/vocabularies.json

sync languages in settings and vocabularies

---

server/requirements.txt

Includes fix for handling genre controlled vocabulary translation

Updates to latest server core v1.10.3

---

client/package.json
server/requirements.txt

Superdesk server core v1.11.2
Superdesk client core v1.11.1

Update cores to latest 1.11

---

client/package.json
server/requirements.txt

Updates Superdesk server and client cores to v1.1.2 and v1.12.1

Releases v1.13-rc2

---

client/package.json
server/requirements.txt

Updates to latest Superdesk server and client cores v1.12.2 and v1.12.1

Update uat v112x

---

client/package.json
server/requirements.txt
server/templates/account_created.html
server/templates/account_created.txt
server/templates/email_layout.html
server/templates/email_layout.txt

add browser info to emails

---

client/package.json
server/requirements.txt

Superdesk client v1.18.1
Superdesk server v1.18.3

Updates to latest available client and server versions

---

client/package.json
server/requirements.txt

Superdesk client v1.18.1
Superdesk server v1.18.3

Updates to latest Superdesk client and server versions

---

client/package.json
server/requirements.txt

Updates to latest available Superdesk server and client cores

---

client/package.json
server/requirements.txt

Superdesk server v1.19.0
Superdesk client v1.19.1

Updates to latest Superdesk cores v1.19

---

client/fidelity/compliance-review/compliance-review.js
client/fidelity/compliance-review/views/compliance-review.html
client/fidelity/index.js
client/superdesk.config.js

SDFID-469
DEPENDS ON: https://github.com/superdesk/superdesk-client-core/pull/2478

Compliance review view

---

client/package.json

Bump client version for compliance review to work

---

client/fidelity/compliance-review/compliance-review.js
client/fidelity/compliance-review/compliance-review.scss
client/fidelity/compliance-review/components/CompliantLifetime.jsx
client/fidelity/compliance-review/components/VersionCreated.jsx
client/fidelity/compliance-review/views/compliance-review.html
client/fidelity/index.js
client/superdesk.config.js

SDFID-490
- Use compliantlifetime metadata date field instead of published date (also replaced in view)
- Show items due in 1 or 3 months
- Show overdue items first (with a visual warning for each)
*This PR needs https://github.com/superdesk/superdesk-client-core/pull/2533

New compliance review view

---

client/fidelity/compliance-review/compliance-review.js
client/superdesk.config.js

Make compliance review view optional in config.features

---

client/fidelity/compliance-review/compliance-review.js
client/fidelity/compliance-review/views/compliance-review.html
client/package-lock.json

The new date filters in `superdesk-client-core` allow this view to be "less hardcoded"

Refactor compliance view new filter format

---

client/fidelity/compliance-review/compliance-status.js
client/fidelity/compliance-review/controllers/ComplianceReviewController.js
client/fidelity/compliance-review/views/compliance-review.html

This solves:
SDIFD-508
SDIFD-509
SDFID-510
SDIFD-511
SDIFD-512
I ended up using `angular.$watch` to filter items **after** they're pulled from the api.

Compliance fixes

---

client/fidelity/compliance-review/controllers/ComplianceReviewController.js
client/fidelity/compliance-review/views/compliance-review.html

This fixes SDFID-508 with infinite scrolling
It also changes how SDFID-509 SDFID-510 SDFID-511 are implemented. The filters are built in the query instead of locally filtering the fetched data.

Query filters instead of local filters

---

client/superdesk.config.js

https://dev.sourcefabric.org/browse/SDFID-482

Changed Date fields to correct format  (SDFID-482)

---

client/superdesk.config.js

https://dev.sourcefabric.org/browse/SDFID-482

Changed Date fields to correct format

---

client/fidelity/compliance-review/controllers/ComplianceReviewController.js
client/superdesk.config.js
server/fidelity/__init__.py

NOTE: we switch on compliance review by default in settings.

SDFID-517 Access privilege for the Compliance review view.

---

client/fidelity/compliance-review/controllers/ComplianceReviewController.js

SDFID-520
Requires https://github.com/superdesk/superdesk-client-core/pull/2756

Fix filter by compliance lifetime

---

client/fidelity/compliance-review/views/compliance-review.html

SDFID-518
Small css change to fix buttons overlapping

Fix buttons overlapping in small screens

---

server/data/vocabularies.json

[VOCABULARIES] added local_domains

---

client/fidelity/compliance-review/controllers/ComplianceReviewController.js
client/fidelity/compliance-review/views/compliance-review.html

Language filters

---

client/fidelity/subject-matter-expert-review/controllers/subjectMatterExpertReviewController.ts

SDFID-529
DEPENDS ON: https://github.com/superdesk/superdesk-client-core/pull/2819

articled-metadata-collapsed-in-subject-matter-expert-view

---

client/superdesk.config.js

enable nested items in output stage

---

client/fidelity/index.js
client/fidelity/login/login-modal.html

SDFID-357
Depends on https://github.com/superdesk/superdesk-client-core/pull/2835

Override login and hide form

---

client/fidelity/compliance-review/controllers/ComplianceReviewController.js
client/fidelity/compliance-review/views/compliance-review.html

change(compliance): Language filter to exclude english articles

---

client/fidelity/compliance-review/views/compliance-review.html
client/fidelity/login/login-modal.html

When pressing "Problems logging in..." there are two labels:
- Log In
- Sign In (this is the one I'm changing to "Single Sign On")
Also this PR includes a small css fix for the filter buttons in compliance review (hovering shows mouse pointer now)

change(login): Change label on standard login form

---

client/package.json
client/superdesk.config.js
server/requirements.txt

* Updates server core to v1.29.3
* Updates client core to v1.29.2, and
* Disables nested items in the desk output stage

Updates Superdesk cores and disables nested items

---

client/fidelity/index.js
client/superdesk.config.js

DEPENDS ON: https://github.com/superdesk/superdesk-client-core/pull/3188

Improve extension setup

---

server/fidelity/compliance.py

When compliance automatic end-of-life correction task is run, it won't
fail anymore the whole task if one edition is failing. Instead, a
warning is logged for the failing item, and it is skipped.
SDFID-589

[COMPLIANCE] Don't fail all items if one of them fail

---

server/fidelity/content_api_rss.py
server/requirements.txt
server/settings.py

initial rss setup

---

.travis.yml
server/dev-requirements.txt
server/fidelity/content_api_rss.py
server/fidelity/tests/rss_test.py
server/fidelity/utils.py
server/setup.cfg

Add web links to RSS

---

server/fidelity/identifier_generator.py

[INTERNAL IDENTIFIER] don't fail when 'profile' is missing in item

---

server/dev-requirements.txt
server/fidelity/content_api_rss.py
server/requirements.txt

- remove content from feed
SDFID-600

fix rss content handling

---

server/fidelity/content_api_rss.py

use `extra.Summary` field in rss

---

server/requirements.txt

- Fix to extra duplicate items on route packages (internal destinations)

Updates Superdesk Server Core to latest v1.33.3, including:

---

server/fidelity/macros/set_german_and_publish.py

versioning (with `_current_version` is normally handled by Eve), but
because this macro use internal API from the backend, Eve is not
triggered and the versions where not stored correctly in
`archive_versions` collection. This is fixed by the used of
`insert_into_versions` helping method.
Furthermore, the `linked_in_packages` and `published_in_package`
metadata were not set for item duplicated in German.
`groups` and `deleted_groups` are not replicated to German duplicated
when doing a correction, as this would override German duplicates by
original English versions.
SDFID-604, SDFID-605

[MACRO] [SET_GERMAN_AND_PUBLISH] fix versioning and package metadata

---

server/data/vocabularies.json

Adds new Content Type vocabulary for the GDW team

---

server/fidelity/content_api_rss.py
server/fidelity/tests/rss_test.py

[CONTENT API][RSS] update permalink following new requirements

---

server/data/vocabularies.json

Updated strings: "Monthly Insight" and "Quarterly Insight"

Updates Japanese translation strings for GDW Content Type vocabulary

---

server/fidelity/content_api_rss.py
server/fidelity/tests/rss_test.py

When no content type is selected, it now defaults to `article`
SDFID-610

[CONTENT API][RSS] update permalink following new requirements (#345)

---

server/data/content_types.json
server/data/vocabularies.json

[DATA] Add `show-hero-image` vocabulary and `article` content type

---

client/package-lock.json
server/fidelity/identifier_generator.py
server/fidelity/tests/internal_id_test.py
server/settings.py

implement desk specific internal ids
